FROM sfiligoi/prp-htcondor-pool:htcondor-bins

# Note: This container assumes there is a shared /docker-init available

ADD startup.sh /usr/bin/wn-init-startup.sh

CMD ["/usr/bin/wn-init-startup.sh"] 

